[project]
name = "jl2py"
version = "0.1.0"
description = "Python Instrumentation for the Julia runtime"
authors = [
    {name = "Gennadi Ryan", email = "gennadiryan@gmail.com"},
    {name = "Jack Champagne", email = "jackchampagne.r@gmail.com"},
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy (>=2.2.3,<3.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "jl2py" }]
include = ["target/lib/libjl2py.so"]