name = "jl2py"
uuid = "8cc2866d-4e9a-4a4c-a08a-2c1210d8ed21"
authors = ["Gennadi Ryan <gennadiryan@gmail.com> and contributors"]
version = "1.0.1-DEV"

[deps]
Piccolo = "c4671d76-df94-11ed-2057-43d4fd632fad"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
